---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: argocdsecret
spec:
  encryptedData:
    foo: AgBw7ZgYFqUP5a2yvDuEV6YCDh1ndwbpJ2gZ8v7oSJkamkCvlBkSaRnH5pW0MkbI0wn+PW5C46bPUtBebPLoIWq7aRZRUQXAVlcmnsAW6xlB4hF+xVsM6tXZC/pn+9Ur/JqHwr5nPOoWHLg1GowJulpDADBTaNCNBLd7cTh3Mh5pc1Dh5D2h6SK/xq3Hlfrhv1YVFnTPj4hSQLaWoB0PUTUaUE5+etW3prcCdVLc7m4SmmWgpX/yxVIs5/5qKy2X+qC2DrH+K0lbflayQzZxQmyQRYkG33eLvlWf8fYeMYk7U3Gq+eU4PdetF1634CCCWH5ZfvQqCKfKJWG9374nB/nQeZEJFE2Z+GKZpZEwlv8CGUGOG0v8er77x4Z6GelpzQbmvW3Mhj/qzIl0VnLTDUPr/YBTNzhcmK5mX+7FzSSgj2mAsVV1hPrHzUroJTtxPocR4pMJ4f2cYO4hU/q/ho00ond7aBHS1zpZeKngj+B8WS17suYPWRRUHRMexp/SVgPkW1FRRUPp5VLwkYRjs9tpX5IrLv8IuYw3mqacs+A9tDGSF42u5pnwmSYfg+q6QxJbQD5TY67FyRgY3NNvRpTfoxPZqojNb4ukPm/yDTe99lC8ZtQ618Q+xiNMjmPKX9DFe0DHBrA1IKHVuZ+KYRH455D98luuBsPr7tM/ZipbPV5ZrCVUOJwGA/jiG0ybvu1wWh8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: argocdsecret
