apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
     containers:
     - env:
       - name: KUBERNETES_NAMESPACE
         valueFrom:
           fieldRef:
             fieldPath: metadata.namespace
       - name: HOSTNAME
         valueFrom:
           fieldRef:
             fieldPath: metadata.name
       image: nanajanashia/argocd-app:1.0
       name: myapp
       ports:
       - containerPort: 8080
